// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGFCj0jiFeKhN7wtyoYmQjDwN97aGM2Iw',
    appId: '1:571143723733:android:b6dad42c6609e3eccba05c',
    messagingSenderId: '571143723733',
    projectId: 'morelife-3d926',
    storageBucket: 'morelife-3d926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWVF0IBmolVKJ8pqTzKzMVe6iwdmUGnQ4',
    appId: '1:571143723733:ios:3f399fd951027640cba05c',
    messagingSenderId: '571143723733',
    projectId: 'morelife-3d926',
    storageBucket: 'morelife-3d926.appspot.com',
    androidClientId: '571143723733-5vfqs3r4mlqg7q486am84jfhf570834f.apps.googleusercontent.com',
    iosClientId: '571143723733-s6a3mma165cj6grv2c5o3q7e3clt712o.apps.googleusercontent.com',
    iosBundleId: 'com.rorywilson.moreLife',
  );
}
